강의 상세 페이지에서 신입생 정원 추가
wafflestudio/snutt-android pull request #172
Opened 2023-05-28 15:55 UTC by JuTaK97

| 신입생 정원 있을 때 | 신입생 정원 없을 때|
| ----- | ----- |
| <img src="https://github.com/wafflestudio/snutt-android/assets/88367636/a557c535-7f74-4ac7-bf5d-075b9903652b" width = 320 /> | <img src="https://github.com/wafflestudio/snutt-android/assets/88367636/f81bf296-2d10-4392-bdee-46d9866f6dd4" width = 320 /> |

2023-05-30 17:54 UTC, eastshine2741 requested changes

2023-05-30 17:54 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/lecture_detail/LectureDetailPage.kt
> +        modifier = Modifier.padding(horizontal = 20.dp, vertical = 20.dp)
Modifier.background(SNUTTColors.White900)넣어줘야 할듯? 다크모드에서 색이 어색해요

2023-05-31 15:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/lecture_detail/LectureDetailPage.kt
> +        modifier = Modifier.padding(horizontal = 20.dp, vertical = 20.dp)
[2543208](https://github.com/wafflestudio/snutt-android/pull/172/commits/2543208eb6c93168d02984289a9300a7382f5ece)

2023-05-31 16:59 UTC, eastshine2741 approved these changes

2023-07-23 11:23 UTC, merged