선택된 시간표 삭제 기능
wafflestudio/snutt-android pull request #179
Opened 2023-06-26 08:02 UTC by eastshine2741

현재 선택된 시간표를 삭제할 수 없는 것이 유저 입장에서 불편하게 다가온다(동기들한테 물어봄)

현재 시간표를 삭제하려 하면
* 현재 시간표가 유일한 시간표일 경우
** 삭제 불가능
* 다른 시간표도 있을 경우
** 같은 coursebook의 시간표가 있는 경우
*** drawer 상에서 다음 시간표를 선택 후 삭제
*** 다음 시간표가 없는 경우 앞 시간표 선택 후 삭제
** 같은 coursebook의 시간표가 없는 경우
*** 다음 coursebook의 시간표 중 첫 번째 선택 후 삭제
*** 다음 coursebook의 시간표가 없는 경우 앞 coursebook의 시간표 중 마지막 선택 후 삭제
하도록 구현했다.

2023-06-26 08:10 UTC, eastshine2741 commented on app/src/main/res/values/strings.xml
> +    <string name="home_drawer_delete_table_unable_alert_message">최소 1개의 시간표가 있어야 합니다.</string>
이거 메시지 괜찮나요?

2023-06-26 08:12 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return tableRepository.tableMap
질문: 원래는 return tableRepository.tableMap.value.size != 1 이었는데 다른 코드들에서 stateflow에 filterNotNull().first()쓰고있길래 일단 그렇게 함... filterNotNull()을 하는 이유가 뭔가요??

2023-06-26 12:25 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return tableRepository.tableMap
내부 값이 nullable일 수 있는 StateFlow가 있어서 (예: CurrentTableRepository의 currentTable) 일괄로 붙인 것 같네영

2023-06-26 12:25 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return tableRepository.tableMap
없어도 상관 없음!

2023-06-26 12:43 UTC, JuTaK97 requested changes

2023-06-26 12:43 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        ) {
어차피 suspend 함수 내라서 상관없긴 한데, 여기는
```suggestion
        if (currentTableRepository.currentTable.value?.id == tableId) {
```
로 간단하게 쓰는 게 나을듯
밑에 있는 `checkTableThemeChangeable`에서 좀 쓸데없이(?) first()를 썼는데 지금과 같이 현재 값만 볼 때는 그냥 `.value` 쓰면 됨! StateFlow가 이런 걸 하기 위해 있는 거니까

2023-06-26 12:43 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        ) {
StateFlow가 아니라 그냥 Flow였으면, `.value`같은 건 없고 무조건 suspend 함수 내에서 `.first()`로 가져와야 하는데 StateFlow는 코루틴 내부가 아니어도 막 value의 최신 값을 가져올 수 있지

2023-06-26 12:43 UTC, JuTaK97 commented on app/src/main/res/values/strings.xml
> +    <string name="home_drawer_delete_table_unable_alert_message">최소 1개의 시간표가 있어야 합니다.</string>
```suggestion
    <string name="home_drawer_delete_table_unable_alert_message">해당 학기에 최소 1개의 시간표가 있어야 합니다.</string>
```
는 어떰?

2023-06-26 12:44 UTC, JuTaK97 reviewed
전반적인 의견 :
1. `deleteTable` 함수는 "테이블 id를 받아서 테이블을 지운다"의 기능만 하게 냅두고, 현재 table을 지운다면 다음 currentTable은 뭐가 되어야 하는지 정하고 switch하는 부분은 별도의 함수로 분리하는 게 좋을 것 같다.
2. 해당 학기에 시간표가 1개면 다른 학기로 넘어가지 말고, 학기별로 시간표가 1개 초과일 때만 지울 수 있게 하는 게 더 자연스럽지 않을까?

2023-06-26 12:57 UTC, JuTaK97 requested changes

2023-06-26 12:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            .first().size != 1
여기도, 역시 
``` suggestion
    fun checkTableDeletable(): Boolean {
        return tableRepository.tableMap.value.size > 1
    }
```
같은 식으로 고고

2023-06-26 12:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return tableRepository.tableMap
그런데 tableMap은 학기 구분 없이 모든 시간표들에 대해서 TableId -> SimpleTableDto의 Map이라서 이렇게 하면 안돼

2023-06-26 12:58 UTC, JuTaK97 requested changes

2023-06-26 12:58 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return tableRepository.tableMap
근데 TableMap은 모든 학기의 시간표에 대해서 시간표의 tableId -> SimpleTableDto의 Map이라 이렇게 하면 안돼

2023-06-26 13:03 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +    suspend fun checkTableDeletable(): Boolean {
```suggestion
    fun checkTableDeletable(tableId: String): Boolean {
        val tableToDelete = tableRepository.tableMap.value[tableId] ?: return false
        return tableRepository.tableMap.value.values.filter {
            it.semester == tableToDelete.semester && it.year == tableToDelete.year
        }.size > 1
    }
```
요런식으로 (구체적인 코드는 입맛대로 ㄱㄱ)

2023-06-26 14:18 UTC, eastshine2741 commented
> 전반적인 의견 :
> 
> 1. `deleteTable` 함수는 "테이블 id를 받아서 테이블을 지운다"의 기능만 하게 냅두고, 현재 table을 지운 다음에 currentTable은 뭐가 되어야 하는지 반환하는 함수를 새로 만드는 게 어떨까?
> 2. 해당 학기에 시간표가 1개면 다른 학기로 넘어가지 말고, 학기별로 시간표가 1개 초과일 때만 지울 수 있게 하는 게 더 자연스럽지 않을까?

상세한 리뷰 고맙습니당!!🧇 1은 그게 더 좋은 것 같고, 2는 궁금한 게 있어요. 목적을 생각해보자면 유저들로 하여금 현재 선택된 시간표의 삭제를 다른 시간표의 삭제와 거의 비슷하게 느끼게 하는 건데, 선택되지 않은 시간표의 삭제는 그 시간표가 어떤 학기의 유일한 시간표더라도 가능함. 따라서 전체 시간표 중에서 유일한 시간표를 삭제하려고 할 때만 막으면 될 것 같은데.... 어떻게 생각하시나요

2023-06-26 14:30 UTC, JuTaK97 commented
> > 전반적인 의견 :
> > 
> > 1. `deleteTable` 함수는 "테이블 id를 받아서 테이블을 지운다"의 기능만 하게 냅두고, 현재 table을 지운 다음에 currentTable은 뭐가 되어야 하는지 반환하는 함수를 새로 만드는 게 어떨까?
> > 2. 해당 학기에 시간표가 1개면 다른 학기로 넘어가지 말고, 학기별로 시간표가 1개 초과일 때만 지울 수 있게 하는 게 더 자연스럽지 않을까?
> 
> 상세한 리뷰 고맙습니당!!🧇 1은 그게 더 좋은 것 같고, 2는 궁금한 게 있어요. 목적을 생각해보자면 유저들로 하여금 현재 선택된 시간표의 삭제를 다른 시간표의 삭제와 거의 비슷하게 느끼게 하는 건데, 선택되지 않은 시간표의 삭제는 그 시간표가 어떤 학기의 유일한 시간표더라도 가능함. 따라서 전체 시간표 중에서 유일한 시간표를 삭제하려고 할 때만 막으면 될 것 같은데.... 어떻게 생각하시나요

현재 선택된 시간표가 현재 학기의 유일한 시간표일 때는 삭제를 못하게 막는 게 어떨지?
다른 학기로 넘어가면 좀 이상할 것 같음

2023-06-26 14:31 UTC, JuTaK97 commented
iOS랑도 얘기해서 맞춰야되니 스크럼때 얘기해야겠네

2023-06-26 14:33 UTC, eastshine2741 commented
> > > 전반적인 의견 :
> > > 
> > > 1. `deleteTable` 함수는 "테이블 id를 받아서 테이블을 지운다"의 기능만 하게 냅두고, 현재 table을 지운 다음에 currentTable은 뭐가 되어야 하는지 반환하는 함수를 새로 만드는 게 어떨까?
> > > 2. 해당 학기에 시간표가 1개면 다른 학기로 넘어가지 말고, 학기별로 시간표가 1개 초과일 때만 지울 수 있게 하는 게 더 자연스럽지 않을까?
> > 
> > 
> > 상세한 리뷰 고맙습니당!!🧇 1은 그게 더 좋은 것 같고, 2는 궁금한 게 있어요. 목적을 생각해보자면 유저들로 하여금 현재 선택된 시간표의 삭제를 다른 시간표의 삭제와 거의 비슷하게 느끼게 하는 건데, 선택되지 않은 시간표의 삭제는 그 시간표가 어떤 학기의 유일한 시간표더라도 가능함. 따라서 전체 시간표 중에서 유일한 시간표를 삭제하려고 할 때만 막으면 될 것 같은데.... 어떻게 생각하시나요
> 
> 현재 선택된 시간표가 현재 학기의 유일한 시간표일 때는 삭제를 못하게 막는 게 어떨지? 다른 학기로 넘어가면 좀 이상할 것 같음

음.....그게 더 크게 작용할 수도 있겠네 그렇게 해볼게여

2023-06-26 16:02 UTC, eastshine2741 commented
피드백 주신거 반영해봤어요! 메일로 온 피드백들도 참고했는데 깃헙 PR 페이지에서 안보이는 것들도 있더라고? 삭제된 코멘트들인가 암튼 걔네도 참고함
더 개선할 점 있다면 알려주세요

2023-06-27 09:31 UTC, JuTaK97 commented
안보이는 건 내가 이상한소리를 해서 삭제했기 때문이지  😆

2023-06-27 12:47 UTC, JuTaK97 requested changes

2023-06-27 12:47 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            newTableId = if (index == siblingTables.size - 1) {
```suggestion
            val newTableId = if (index == siblingTables.size - 1) {
```

2023-06-27 12:47 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            val newTableId: String
```suggestion
```

2023-06-27 12:47 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        }.size > 1
이렇게 하면, 현재 선택한 시간표를 삭제할 때 그 학기에 시간표가 그거뿐일 때 문제가 되지 않나?

2023-06-27 12:51 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            it.semester == tableToDelete?.semester && it.year == tableToDelete.year
이 로직 꽤 자주 나오는데, SimpleTableDto에 확장함수로 하나 만들면 좋을듯

2023-06-27 13:04 UTC, JuTaK97 requested changes

2023-06-27 13:04 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            it.semester == tableToDelete?.semester && it.year == tableToDelete.year
```suggestion
        if (currentTableRepository.currentTable.value?.id != tableId) return true // 현재 선택중인 시간표가 아니면 무조건 삭제 가능

        val tableToDelete = tableRepository.tableMap.value[tableId] ?: return false
        return tableRepository.tableMap.value.values.filter { it.isSameCourseBook(tableToDelete) }.size > 1 // 선택중인 시간표일 경우, 해당 학기의 시간표가 2개 이상일 때 삭제 가능
```
이렇게 간단히 쓸 수 있을듯

2023-06-27 13:04 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            val courseBook = CourseBookDto(tableMap.value[tableId]!!.semester, tableMap.value[tableId]!!.year)
!! 있는 건 참을 수가 없어
siblingTables 구하는 건
```suggestion
            val tableToDelete = tableMap.value[tableId] ?: return
            val siblingTables = tableMap.value.values.filter { it.isSameCourseBook(tableToDelete) }
```
이렇게 간단하게 ㄱㄱ (isSameCourseBook는 위에서 말한 새로 만들 SimpleTableDto의 함수)

2023-06-27 13:09 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
물론 지금은 `checkTableDeletable`를 통해 siblingTables의 size가 2 이상이라는 게 보장돼 있지만, 저 함수만 보면 outofindex가 날 수 있는 모양이라서 나중에 혹시 재사용하게 되거나, 맥락을 모르는 사람이 읽으면 이상할 수 있을 것 같음

2023-06-27 13:10 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
그래서 내가 그렸던 그림은 삭제 가능 체크 함수에서 다음 current table이 될 table id를 반환해주고, 이걸 let으로 받아서 deleteTable 때리는 거였긴 함

2023-06-27 15:56 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
🧇🧇그런방법이 있군 수정해봤어요

2023-06-27 15:57 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +            it.semester == tableToDelete?.semester && it.year == tableToDelete.year
확장함수 만들었어요 SimpleTableDto말고 CourseBookDto랑 비교하는 경우도 있길래 오버로드해봄

2023-06-28 00:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/ModelExt.kt
> +fun SimpleTableDto.courseBookEquals(other: SimpleTableDto): Boolean {
네이밍센스 👍

2023-06-28 00:59 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return if (currentTableRepository.currentTable.value?.id == tableId) {
주석도 써있으면 좋을듯

2023-06-28 05:51 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +        return if (currentTableRepository.currentTable.value?.id == tableId) {
추가해봤습니다!

2023-06-30 08:06 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1687970559712909?thread_ts=1687963334.832389&cid=C0PAVPS5T
이거 하다가 궁금해진건데, 대신 선택할 시간표 리턴하는 함수를 따로 분리해야 하는 이유가 있나요? 한 함수 안에서 deleteTable(tableId) 호출하고 바로 changeSelectedTable(tableId) 하는 게 저거 구현하기 편할 것 같아서...

2023-07-02 14:27 UTC, JuTaK97 approved these changes
LGTM 👍

2023-07-06 14:29 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
사실 현재 선택된 시간표의 index를 Flow로 만들어서 viewModel에서 갖고있고 싶었는데, 그 flow를 못만들겠어서 일어난 문제이긴 함ㅠㅠㅠ

2023-07-06 14:29 UTC, JuTaK97 commented
깃헙 웹페이지에서 
<img width="1167" alt="image" src="https://github.com/wafflestudio/snutt-android/assets/88367636/8c4a9595-e6ef-4d51-b94a-338ba8c8362b">

이거 눌러도 되긴 함

2023-07-06 14:32 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
아항 그냥 함수의 역할이 최소한으로 되어있으면 좋지 않을까? <<라는 단순한 욕망에서 한 말이긴했음

2023-07-06 14:33 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
> 사실 현재 선택된 시간표의 index를 Flow로 만들어서

이건 좀 과한듯ㅋㅋ

2023-07-06 14:33 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +                siblingTables[index + 1].id
바로 하는게 나은 거 같으면 바로 ㄱㄱ
함수이름 명확히 바꾸고 주석쓰면 문제없지

2023-07-06 17:16 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +    suspend fun deleteTableAndSwitchIfNeeded(tableId: String) { // 시간표를 삭제하고, 현재 시간표라면 index를 유지하며 다른 시간표를 선택한다
함수 이름 너무 길긴한데 일단 코드는 단순해짐.....ㅎㅎ
좋은 이름 추천 환영

2023-07-08 09:23 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/TableListViewModel.kt
> +    suspend fun deleteTableAndSwitchIfNeeded(tableId: String) { // 시간표를 삭제하고, 현재 시간표라면 index를 유지하며 다른 시간표를 선택한다
나는 좋아

2023-07-08 09:23 UTC, JuTaK97 approved these changes

2023-07-11 14:10 UTC, JuTaK97 commented
리베이스 & 머지 고고

2023-07-12 12:13 UTC, merged