빈자리 알림 UI
wafflestudio/snutt-android pull request #183
Opened 2023-07-02 17:31 UTC by eastshine2741

SearchPage와 SearchListItem의 아름다운 코드를 참고했습니다

2023-07-02 17:33 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
> +                    LectureDto(
빈자리 알림을 등록한 강의의 목록을 가져오는 api가 아직 없어서 임의로 만들었습니다
일단 Paging3 쓴다고 생각하고 짰고, 테스트를 위해 Flow<PagingData<LectureDto>>였던걸 Flow<List<LectureDto>>로 바꿔둠

2023-07-02 17:36 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyListItem.kt
> +    val backgroundColor = if (selected) SNUTTColors.Dim2 else SNUTTColors.Transparent
LectureListItem을 신나게 참고했는데, 피그마 다시 보니 클릭했을 때 색 변화가 좀 다르네... 추후 수정 예정
취소여석 있는 강좌의 배경색 붉게 하는것도 같이 할게요

2023-07-11 08:59 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                val sugangSnuUrl = "https://sugang.snu.ac.kr/sugang/ca/ca102.action?workType=F"
일단 수강스누/수강신청/수강신청으로 이동하게 해놨어용
사용중인 웹브라우저를 모두 종료하고 어쩌고는 안 뜨는 듯? 제 폰에선 그랬음

2023-07-11 08:59 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyListItem.kt
> +fun VacancySticker(
이거 따로 부르는 이름이 있나...? 몰라서 대충 스티커라고 함ㅋㅋㅋㅋ

2023-07-11 09:01 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/Icon.kt
> +    colorFilter: ColorFilter? = ColorFilter.tint(SNUTTColors.Black900),
ClockIcon LocationIcon 다 tint 되어있는데, TagIcon만 안되어있어서 다크모드에서 아이콘 색이 까만색이었다
그래서 수정

2023-07-23 16:02 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                visible = vacancyViewModel.isEditMode,
아이템이 화면을 넘어서 꽉 차있을 때, AnimatedVisibility로 버튼이 사라지면 위의 Box가 애니메이션을 따라 커지는게 아니라, 애니메이션 끝날때까지 가만히 있다가 갑자기 커진다.... 대체왜지???

2023-07-24 16:49 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +        onBackPressed()
원래 방식대로 뒤로가기 처리하면 화면이 꺼졌다 켜졌을 때 콜백이 작동하지 않는 버그가 있었다. 근데 공식에서 지원하는 BackHandler를 쓰니까 버그가 사라졌다! 아마 BackHandler 내부의 rememberUpdatedState 때문이 아닐까 의심중.. LectureDetailPage도 마찬가지의 버그가 발생해서 이걸로 해결할 수 있을 것 같은데, 더 공부해보고 따로 PR 올릴게요

2023-07-29 06:47 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                val sugangSnuUrl = "https://sugang.snu.ac.kr/sugang/ca/ca102.action?workType=F"
이거 remote config로 관리하자

2023-07-29 06:47 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyListItem.kt
> +fun VacancySticker(
굳

2023-07-29 06:51 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +        onBackPressed()
화면이 꺼졌다 켜졌을 때 << 이게 뭐야?

2023-07-29 07:27 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                        if (!vacancyViewModel.isEditMode)
[nit] 가독성 높이기
```suggestion
                        if (vacancyViewModel.isEditMode.not())
```

2023-07-29 07:27 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                            Modifier.pullRefresh(pullRefreshState)
우왕 이런게 있었구나

2023-07-29 07:27 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                PullRefreshIndicator(
이런게 있었네

2023-07-29 07:27 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                visible = vacancyViewModel.isEditMode,
AnimatedVisibility가 동작하는 방식 때문에 그런 거 같은데 자세히는 모르겠다
https://stackoverflow.com/a/71527654 
원하는 걸 하려면 AnimatedVisibility 쓰지 말고, 직접 height랑 offset을 조절해야 할 듯

2023-07-29 07:37 UTC, JuTaK97 commented
근데 Dialog에 elevation 좀 넣어야겠다
![image](https://github.com/wafflestudio/snutt-android/assets/88367636/f13ada6b-da50-4eb8-afd5-f9c9f9cff33e)

Dialog 코드 가서 Surface에다가 elevation 넣으면 됨

<img width="381" alt="image" src="https://github.com/wafflestudio/snutt-android/assets/88367636/1c0c16f4-2a45-4870-a95d-694dfdf819b6">

2023-07-29 10:37 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +        onBackPressed()
화면 자동 꺼짐 시간(기본값 2분)이 지나서 화면이 꺼지거나, 유저가 직접 버튼을 눌러서 화면을 끈 후 시간이 조금 지나면 액티비티가 백그라운드로 들어가는데, 다시 화면을 켜면 뒤로가기 콜백이 작동하지 않더라구
LectureDetailPage에서 편집모드 -> 화면 끄고 조금 기다림 -> 다시 켬 -> 뒤로가기 -> 콜백이 작동하지 않아서 '편집을 취소하시겠습니까' 다이얼로그 없이 바로 뒤로감 << 이런 버그가 있는데 똑같은 이유 같아

2023-07-29 10:51 UTC, eastshine2741 commented
> 근데 Dialog에 elevation 좀 넣어야겠다 ![image](https://user-images.githubusercontent.com/88367636/256970497-f13ada6b-da50-4eb8-afd5-f9c9f9cff33e.png)

오 이거 내 폰에서는 다이얼로그 뒷배경이 어두워져서 몰랐는데 기기마다 다른건가?? 신기하네

2023-07-30 11:58 UTC, JuTaK97 commented
> > 근데 Dialog에 elevation 좀 넣어야겠다
> 
> 오 이거 내 폰에서는 다이얼로그 뒷배경이 어두워져서 몰랐는데 기기마다 다른건가?? 신기하네

아 이거 내가 에뮬레이터에서 봐서 안뜬거일수도 있겠다 나도 폰에서는 섀도우 보임

2023-07-30 12:00 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +        onBackPressed()
아 이거 가끔 그러길래 어? 내가 잘못봤나? 생각했는데 이렇게 재현이 되는구나

2023-08-03 21:28 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/settings/UserViewModel.kt
> +        if (it.isEmpty()) {
배너 표시 관련된 로직을 어디에 넣어야 할까...하다가 UserViewModel에 넣었어요
빈자리페이지에 뜨는 게 아니어서 VacancyViewModel에 들어가는 게 어색하다는 생각도 들었고, config api랑 같이 쓸테니까 UserViewModel에 있는 게 좋지 않을까 해서

2023-08-03 21:30 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/settings/UserViewModel.kt
> +        if (it.isEmpty()) {
Config api가 어디에 들어갈지도 고민해봐야 하는데, 일단 UserViewModel이라고 생각했어요. firstBookmarkAlert처럼 꼭 유저 정보 관련된 게 아닌 애매한 것들도 UserViewModel에 들어가 있길래

2023-08-03 21:33 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                            shareScreenshotFromView(view, context, topBarHeight, if (shouldShowVacancyBanner) bannerHeight else 0, timetableHeight)
어차피 친구기능 나오면서 스샷으로 하는 공유는 사라질 테니 중요한 건 아니지만
스샷 찍을 때 topBarHeight + bannerHeight 만큼 자르고 찍도록 했는데, 왜인지 스샷 위쪽에 배너가 몇 픽셀 정도 보임... 일단 급한 것들 끝내고 다시 볼게요 
![image](https://github.com/wafflestudio/snutt-android/assets/68140623/27d8049d-0c23-40b7-a973-650954708def)

2023-08-03 21:37 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/settings/UserViewModel.kt
> +    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(), true)
stateIn 이렇게 쓰는 거 맞나요? 특히 SharingStarted.WhileSubscribed()가 걸리는데... 구독자가 있을 때만 작동하는 거라고 이해했고, 의도랑 맞는 것 같아서 썼어요 일단 잘 동작함
근데 compose에서 구독자는 뭐에요? collectAsState()하는 변수인가

2023-08-03 21:40 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            key = "vacancy_banner_close_date",
firstVacancyVisit이랑 vacancyBannerCloseDate 둘 다 domain으로 DOMAIN_SCOPE_LOGIN을 넣었는데, 아래에 ```//레거시 대응을 위해 어쩔 수 없음...``` 이라 되어있어서 좀 걸림... 무슨뜻이에요??
로그인 되어있는 동안 유지되고, 로그아웃하면 사라지는 prefValue라는 뜻으로 이해했고, 의도랑 맞아서 썼어요

2023-08-03 21:47 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +            )
[여기](https://github.com/wafflestudio/snutt-android/pull/183#discussion_r1278263283)에서 이야기한 거 적용해보려고 했는데, height를 animatedDp로 해서 LazyColumn 영역 크기를 바꿔봤자 LazyColumn 내에서의 스크롤은 그대로여서 해결되지 않았음ㅠㅠ
그래서 삭제 버튼이 올라올 때 아이템이 가려지는 것만이라도 고치자! 라는 생각으로 넣은 코드.
맨 아래까지 스크롤 된 상태에서 삭제 버튼이 올라오면 자동으로 스크롤해서 맨 아래 아이템이 가려지지 않도록 했어요
근데 버튼이 올라오는 속도보다 LazyColumn이 스크롤되는 속도가 조금 느려서 덜 이쁨....

2023-08-04 15:30 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +        prefContext,
스크럼에서 firstVacancyVisit 관련해서 버그 있다고 이야기했는데, 버그가 아니고 로그아웃하면서 PrefValue가 날아간거인 듯..ㅋㅋㅋ

2023-08-04 15:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/RoundCheckbox.kt
> +                }
[nit] 코틀린스럽게 쓰기
```suggestion
                onCheckedChange?.invoke(checked.not())
```

2023-08-04 15:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            key = "vacancy_banner_close_date",
내가 오기 훨씬 전 레거시인 것 같아서 잘 모르겠지만 구 버전에서 저 string을 쓰고 있어서, SCOPE 의미에 맞게 string을 바꾸고 싶어도 못 바꾼다는 의미인 것 같네

[여기](https://github.com/wafflestudio/snutt-android/blob/ff526daa27cc3ea0d3a9e86e154b7761279d00fa/app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt#L175) 보면 로그아웃 할 때마다 DOMAIN_SCOPE_LOGIN이랑 DOMAIN_SCOPE_CURRENT_VERSION 둘다 지워지고 있는데, 뭔가 히스토리가 있어 보이긴 하지만 우리 앱에서 막 복잡하게 관리하고 그럴 거 없으니 그냥 DOMAIN_SCOPE_LOGIN로 써도 될듯함

2023-08-04 15:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepository.kt
> +    suspend fun setVacancyVisited()
ㅋㅋㅋ 줄바꿈 일관성 부탁

2023-08-04 15:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                            shareScreenshotFromView(view, context, topBarHeight, if (shouldShowVacancyBanner) bannerHeight else 0, timetableHeight)
TopBar() 코드 보면, globallypositioned로 높이 재는 modifier가 상위 Surface가 아니라 내부 Column에 붙어 있어서 그런듯
파라미터로 받는 modifier를 Surface에 넣어 보고 어색한 부분 없는지 체크 ㄱㄱ

2023-08-04 16:30 UTC, JuTaK97 reviewed
아주좋다

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/LectureDto.kt
> +    @Json(name = "wasFull") val wasFull: Boolean = false,
초기값 적용 굳!
과거 필드들 중에서 초기값이 없는 게 좀 있어서, 만약 누군가의 실수로 필드가 빠지면 앱이 터지는 사태가 발생함

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/ui/Colors.kt
색깔은 날잡고 싹 정리합시다

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/NavigationDestination.kt
> +    const val VacancyNotification = "vacancy"
딥링크 scheme이 이거여야 됨!!!
서버랑 iOS랑 이야기가 꼭 되어야 하고, https://www.notion.so/wafflestudio/44979462a3fa438195b6423286d16cc5 에 기입 부탁해

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/bookmark/BookmarkPage.kt
> +) {
이것도 언젠가 얘기하려 했는데, 파라미터로 뷰모델을 전달하는 건 사실 절대 좋은 형태가 아니야
무조건 전부 다 콜백으로 전달해서, 뷰모델을 쓰는 케이스 하나하나 다 콜백 파라미터로 전달해서 하는 게 "올바른" 사용법이긴 해

근데 그렇게 하면 코드 가독성이 진짜 심각할 정도로 망가져서(특!히! LectureListItem) 이렇게 한 거라는 것을 알아두면 좋을 것 같아

이거에 대해 아키테처적으로 고민을 많이 하고 대응을 하면 좋을 것 같은데... 최근에 [UseCase](https://heegs.tistory.com/58) 비슷하게 잘 만들면 예쁘고 철학에도 맞지 않을까 고민하고 있긴 했어

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/search/LectureListItem.kt
> +                Spacer(modifier = Modifier.weight(0.3f))
요것들 5개 굉장히 겹치는 거 아닌가? 별도 컴포넌트로 분리하는 게 더 깔끔할 것 같은데, 실제로 깔끔해진다면 적용 고고

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/settings/UserViewModel.kt
> +        if (it.isEmpty()) {
조와용

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/settings/UserViewModel.kt
> +    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(), true)
이것도 리서치를 좀 해 봐야 되는데 아마 구독자는 collect하는 곳이 맞는걸로 알고 있고, strategy는 뭐로 하든 큰 차이 없는 것 같아서 일단 적당히 아무거나 쓴 것

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                            )
이거 ./gradlew ktlintFormat 하면 고쳐지는 거 ㅋㅋㅋㅋ  위아래로 늘어지는 거 싫어서 내가 꾸역꾸역 안 고치고 있었는데 드디어 바뀌는구만

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                )
이거 내가 이렇게 해 놓은게 많은데, 사실 이렇게 하면 됨
```suggestion
                style = SNUTTTypography.body2,
                color = SNUTTColors.AllWhite,
```

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +            )
충분히 괜찮은듯! release 버전 빌드 뽑아보면 더 부드러울거야

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                                modalState.hide()
알고있을법한 TMI: 
modalState.hide()을 launchSuspendApi{} 안에 넣어놓으면 api 콜에서 에러가 났을 때 모달이 안 닫히고, 유저는 뭔가 조치를 취한 후 확인을 바로 다시 누를 수 있음
지금은 ㄱㅊ을 거 같은데, 모달을 띄우고 확인을 누르기까지 뭔가 "무척 귀찮은 액션"을 거친다면 modalState.hide() 를 api 콜과 같은 try-catch 블록에 넣는 걸 추천

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
> +                    HorizontalPager(
튜토리얼 페이지에서 유기된 Pager의 화려한 재등장

2023-08-04 16:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
다크모드는 추후 대응?

2023-08-04 16:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
[1576ad3](https://github.com/wafflestudio/snutt-android/pull/183/commits/1576ad31c81fa31c19c52b569d613592a7aaeb76) 에서 된건가

2023-08-05 00:50 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                            shareScreenshotFromView(view, context, topBarHeight, if (shouldShowVacancyBanner) bannerHeight else 0, timetableHeight)
바쁜데 상세한 리뷰 고맙습니다....최고
넣어봤는데 잘 돼요! 이대로가겟슴다

2023-08-05 00:55 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/vacancy_noti/VacancyPage.kt
넹넹

2023-08-06 07:10 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                            )
ㅋㅋㅋㅋㅋㅋ되돌림ㅎㅎ 한줄이 확실히 이쁘다
근데 github action에서 돌아가는 ci 맞추려고 ./gradlew ktlintFormat 하는 거 아니었어? ktlintFormat에 어긋난건데 그동안 어떻게 ci는 통과했던거야? ci가 ktlintformat보다 덜 엄격한건가

2023-08-06 07:10 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/search/LectureListItem.kt
> +                Spacer(modifier = Modifier.weight(0.3f))
LectureListItemButton 새로 만들어서 정리했으

2023-08-06 07:18 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            domain = DOMAIN_SCOPE_PERMANENT,
remote config는 유저 관련된 게 아니므로
* 로그인 할 때가 아닌 앱이 켜질 때 HomeViewModel의 refreshData()에서 fetchRemoteConfig() 호출
* 로그아웃 할 때 remoteConfig PrefValue가 지워질 필요도 없으므로 DOMAIN_SCOPE_PERMANENT
근데 DOMAIN_SCOPE_PERMANENT가 지금까지 쓰인 적이 없어서 이렇게 쓰는 게 맞는지 확신이 안듦... 맞나요

참고로 fetchRemoteConfig()는 UserViewModel에 있긴 해요...어디 둘지 마땅치가 않아서... 다른 장소 좋은 데 있나요

2023-08-06 07:20 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "vacancyNotificationBanner") val vacancyBannerOn: Boolean = false,
dto 이렇게 하면 되나요? ReactNativeBundleSrc는 Map<String,String> 하나 가지고 있는 data class

2023-08-06 07:48 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            domain = DOMAIN_SCOPE_PERMANENT,
remoteConfig는 별도 객체로 최상위에서 생성하고 앱 켤때마다 수신 받은 후, 하위로 전파하는 식으로 할까

2023-08-06 07:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "vacancyNotificationBanner") val vacancyBannerOn: Boolean = false,
아 뭔가 더 이쁘게 하고싶다

2023-08-06 08:28 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/home/timetable/TimetablePage.kt
> +                            )
아마 그런 거 같음

2023-08-06 08:30 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "reactNativeBundleFriendGst") val friendgst: ReactNativeBundleSrc?,
Gst는 우현민이 낸 오타 비슷한 거라고 했는데

2023-08-06 08:31 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            domain = DOMAIN_SCOPE_PERMANENT,
아 popupState처럼 별도 객체로 만들고 CompositionLocal로 내려주기? SNUTTStorage 사용하지 않고?
난 좋아! 사실 config를 저장할 필요가 있긴 한가도 의문이었음

2023-08-06 08:52 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "vacancyNotificationBanner") val vacancyBannerOn: Boolean = false,
근데 이렇게 해도 괜찮을듯

2023-08-06 08:53 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            domain = DOMAIN_SCOPE_PERMANENT,
ㅋㅋㅋ popupState가 그렇게 생겼던 이유는 Jetpack Compose 리팩 전 기능이라 그런거였긴해,,....

2023-08-06 09:22 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "vacancyNotificationBanner") val vacancyBannerOn: Boolean = false,
근데 이거 파싱이 map으로 자동으로 안될거같은데

2023-08-06 09:37 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "vacancyNotificationBanner") val vacancyBannerOn: Boolean = false,
혹시 몰라서 테스트해봤는데 map으로 잘 돼요!

2023-08-06 10:39 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/SNUTTStorage.kt
> +            domain = DOMAIN_SCOPE_PERMANENT,
CompositionLocal 이용하도록 바꿔봤어용

2023-08-06 10:40 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/dto/core/RemoteConfigDto.kt
> +    @Json(name = "vacancyNotificationBanner") val vacancyBannerOn: Boolean = false,
실제 내려오는 json이랑 다르길래 조금 수정했어요

2023-08-06 12:25 UTC, JuTaK97 commented
RemoteConfig 전파하는 쪽은 내가 이따 함 정리해서 여기에 커밋 푸시해봄

2023-08-06 12:44 UTC, JuTaK97 commented
근데 진짜 map 형태 파싱이 됨? 안 되는 것 같은데

2023-08-06 13:20 UTC, JuTaK97 commented
는 앱버전 문제 ㅋㅋㅋㅋ

2023-08-06 13:36 UTC, JuTaK97 commented
근데 vacancyBannerCloseDate 를 굳이 저장하는 이유가 뭐임?

2023-08-06 14:50 UTC, eastshine2741 commented
닫은 날 동안은 안보이다가 다음 날부터 보여야 해서! 마지막으로 배너를 닫은 날짜를 저장하고, 현재 날짜가 그 날짜보다 이후일 때에만 보여주고있음

2023-08-08 13:43 UTC, eastshine2741 commented
VacancyBannerConfig.kt, VacancyUrlConfig.kt 등 전부 network.dto.core에 있었는데 좀 안어울리는 것 같아서 network.dto.config로 뺐어요

2023-08-08 16:40 UTC, JuTaK97 commented
> 닫은 날 동안은 안보이다가 다음 날부터 보여야 해서! 마지막으로 배너를 닫은 날짜를 저장하고, 현재 날짜가 그 날짜보다 이후일 때에만 보여주고있음

그러면 굳이 String으로 저장하지 말고 그냥 Long으로 저장하는 건 어때 (사실 상관없긴함)
Popup 다시보지 않기, 닫기 로직이 그렇게 되어 있거든

2023-08-09 06:49 UTC, eastshine2741 commented
> 그러면 굳이 String으로 저장하지 말고 그냥 Long으로 저장하는 건 어때 (사실 상관없긴함)
Popup 다시보지 않기, 닫기 로직이 그렇게 되어 있거든

이렇게 수정했음! 확실히 보기좋아졌다👍

2023-08-09 06:50 UTC, eastshine2741 commented
> VacancyBannerConfig.kt, VacancyUrlConfig.kt 등 전부 network.dto.core에 있었는데 좀 안어울리는 것 같아서 network.dto.config로 뺐어요

popupState처럼 nested class로 바꿨어요

2023-08-09 06:51 UTC, eastshine2741 commented
거의 릴리즈할 정도 된듯? RemoteConfig 전파하는 것만 수정되면 릴리즈 할까요

2023-08-09 06:58 UTC, JuTaK97 commented
오늘밤에 바로 해봄 최우선으로

2023-08-09 13:17 UTC, JuTaK97 requested changes

2023-08-09 13:17 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
>      }
Java Calendar는 맨날 사람들이 별로라고 쓰지 말라고 하는 라이브러리라고 들었음

```suggestion
    override suspend fun updateVacancyBannerOpenTime() {
        val today = TimeUnit.MILLISECONDS.toDays(System.currentTimeMillis())
        val nextOpenDayInMillis = TimeUnit.DAYS.toMillis(today + 1)
        storage.vacancyBannerOpenTime.update(nextOpenDayInMillis)
    }
```

2023-08-09 13:19 UTC, JuTaK97 reviewed
베리굿

2023-08-09 13:30 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
>      }
ㅋㅋㅋㅋㅋㅋ아 그래? 찾아보니까 꽤 많은 [문제점](https://sujl95.tistory.com/3)이 있네... 리턴 타입을 예측하기 힘들고, 월 enum이 0 based라 불편하고, mutable하다
저걸로 수정할게요

2023-08-09 15:56 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
>      }
근데 이거 뭔가 다르게 동작하는데... TimeUnit.MILLISECONDS.toDays가 timezone에 영향을 받아? System.currentTimeMillis()는 timezone 상관 없이 현재 기기의 locale(한국) 기준으로 측정되는데, vacancyBannerOpenTime에 저장되는 값이 UTC로 저장되어서 좀 다르게 동작함... 일단 계속 알아보는중

2023-08-09 15:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
>      }
상관없지않아?

2023-08-09 15:58 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
>      }
아 KST로 자정에 바뀌는 걸 원하는건가 ㅋㅋㅋ

2023-08-09 16:00 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/data/vacancy_noti/VacancyRepositoryImpl.kt
>      }
8월 9일 오후 11시로 시간 설정 -> 배너 지우기 -> 8월 10일 오전 12시로 시간 설정 -> 배너가 떠야하는데 뜨지 않는다!

2023-08-09 16:16 UTC, JuTaK97 approved these changes
가즈아~~ 수고많았다

2023-08-09 16:23 UTC, merged