튜토리얼 페이지 리팩토링
wafflestudio/snutt-android pull request #186
Opened 2023-07-07 14:30 UTC by eastshine2741

뚝딱뚝딱

2023-07-07 14:31 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/EditTextWIthTitle.kt
> +    leadingIcon: @Composable (() -> Unit) = {},
피그마 보니까 Text랑 EditText가 자꾸 같이 나오길래 합쳐서 하나로 만들었는데 괜찮나요..?

2023-07-08 09:50 UTC, JuTaK97 commented
👷

2023-07-08 09:51 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/EditTextWIthTitle.kt
> +    leadingIcon: @Composable (() -> Unit) = {},
굳이 싶긴 함

2023-07-08 16:15 UTC, eastshine2741 commented
![KakaoTalk_20230709_010955861](https://github.com/wafflestudio/snutt-android/assets/68140623/1bdaa9cb-0e92-4fe8-b2dc-66a4dacd6ae5)
![KakaoTalk_20230709_010955861_01](https://github.com/wafflestudio/snutt-android/assets/68140623/29ea58e5-5fbd-41aa-bffc-5cdad5e47710)
![KakaoTalk_20230709_010955861_02](https://github.com/wafflestudio/snutt-android/assets/68140623/a25fe9bf-be2f-4bb9-a565-865337fde5c5)
![KakaoTalk_20230709_010955861_03](https://github.com/wafflestudio/snutt-android/assets/68140623/3b9d45e2-5e2f-4f6e-bffb-919752cc1975)

이상하게 보이는 거 있다면 알려주세용

2023-07-09 05:35 UTC, JuTaK97 requested changes
아주좋아 너무좋아

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification")
```suggestion
    @POST("/v1/user/email/verification")
```

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification/code")
```suggestion
    @POST("/v1/user/email/verification/code")
```

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/TutorialPage.kt
> +                apiOnProgress.hideProgress()
여기가 좀 옛날 코드인데
```
            launchSuspendApi(apiOnProgress, apiOnError) {
                apiOnProgress.showProgress(context.getString(R.string.sign_in_sign_in_button))
                val loginResult = facebookLogin(context)
                userViewModel.loginFacebook(
                    loginResult.accessToken.userId,
                    loginResult.accessToken.token
                )
                homeViewModel.refreshData()
                navController.navigateAsOrigin(NavigationDestination.Home)
            }
```
로 깔끔하게 고고

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignInPage.kt
> +    val buttonEnabled by remember { derivedStateOf { idField.isNotEmpty() && passwordField.isNotEmpty() } }
false일 때는 버튼 눌러도 API 안 쏘게 하는 게 좋을듯

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignInPage.kt
> -        }
여기도 마찬가지로 launchSuspendApi 써서 중복 코드 제거 고고

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignInPage.kt
> +                        hint = stringResource(R.string.sign_in_id_hint),
힌트 문구는 `아이디를 입력하세요`랑 `비밀번호를 입력하세요`로 가자

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignInPage.kt
> +                        style = SNUTTTypography.subtitle2,
아이디 찾기랑 비밀번호 재설정 버튼 텍스트 색깔 Black600로 하자

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignUpPage.kt
> +                verticalArrangement = Arrangement.spacedBy(16.dp),
좀만 더 넓히면 어떰? 한 20dp정도로

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignUpPage.kt
> +                    verticalArrangement = Arrangement.spacedBy(6.dp)
얘도 한 10정도로

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
`EmailVerificationpage` 로 변경하기
NavigationDestination이랑 통일

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
이거진짜 부끄러운 똥코드인데 빨리 고치고싶다

2023-07-09 05:35 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
플로우 변경 : 확인 / 나중에 하기 중 확인 눌렀을 때 바로 로컬 이메일로 전송하지 말고, `{유저가 채울 곳}@snu.ac.kr` 의 EditText 있는 창 추가하기

2023-07-09 05:39 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
시작 시간을 저장하고 currentTime을 기준으로 비교하는 형태로 바꿔야됨

2023-07-09 11:53 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
근데 이제 가입 시에 스누메일만 받을거고, 그걸로 이메일인증까지 다 할거니까 이메일을 따로 받을 필요 없지 않아?
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1688741533676329?thread_ts=1688739784.403309&cid=C0PAVPS5T
난 이거 그렇게 이해함

2023-07-09 11:56 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification/code")
v1 무슨뜻이에요? 깃헙 위키 보니까 v1붙은것도 있고 안붙은것도 있는데, 깃헙 위키 기준 저 api는 v1 없긴함...

2023-07-09 12:00 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignInPage.kt
> +    val buttonEnabled by remember { derivedStateOf { idField.isNotEmpty() && passwordField.isNotEmpty() } }
아하.. 그럼 WebViewStyleButton에 enabled 같은 파라미터 만들어서 enabled=true일 때에만 onClick 실행하는건 어때? enabledColor랑 disabledColor도 만들어서 enabled에 맞게 색깔 표시하도록 하고

2023-07-09 12:51 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignInPage.kt
> +    val buttonEnabled by remember { derivedStateOf { idField.isNotEmpty() && passwordField.isNotEmpty() } }
너무좋지

2023-07-09 12:56 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification/code")
옛날 API, 최근 API
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1674299858943189?thread_ts=1674216364.737819&cid=C0PAVPS5T
https://wafflestudio.slack.com/archives/C0PAVPS5T/p1684761304631579?thread_ts=1684717827.550599&cid=C0PAVPS5T

2023-07-09 12:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
아 맞네 그래서 가입 화면(EditText 4개 있는 화면)에서 @snu.ac.kr 이 고정으로 박혀있는 거로 하자고 했었던 것 같네

2023-07-09 13:37 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification/code")
아 v1 붙은 새 api로 점점 넘어가고있는건가? v1 없는 옛날 api들에 v1 붙여도 잘 작동하네

2023-07-09 15:48 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
ㅋㅋㅋㅋㅋㅋㅋ 코루틴에서 1초씩 딜레이하는게 아니라 현재시간-타이머 시작시간을 계산해야 한다는 뜻이야? 1초씩 딜레이하는게 안좋은 방법이야...?

2023-07-09 16:26 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/EditText.kt
> +                        ) {
이메일 입력, 인증코드 입력 등 trailingIcon을 사용할 때, 텍스트를 너무 많이 입력하면 trailingIcon이 이상하게 표시되고 있었음 -> 텍스트에 weight 1f인 Box 씌워서 해결했는데 괜찮나요..?

2023-07-11 06:08 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification/code")
release 3.1.5에서 다 붙었구나

2023-07-11 06:20 UTC, eastshine2741 commented
<img src="https://github.com/wafflestudio/snutt-android/assets/68140623/4dce2b29-766e-49ff-9490-72290ea78b96" width="180" height="400"/>
<img src="https://github.com/wafflestudio/snutt-android/assets/68140623/9af865ba-1981-47a5-b88b-25ac7befd69a" width="180" height="400"/>
<img src="https://github.com/wafflestudio/snutt-android/assets/68140623/8c40eed4-6793-435c-8c16-5ce5eceee206" width="180" height="400"/>
<img src="https://github.com/wafflestudio/snutt-android/assets/68140623/a8d5f6a7-bea2-48bf-b535-4bb174e48743" width="180" height="400"/>

수정된 버전

2023-07-11 13:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/EditText.kt
> +                        ) {
👍 
원래는 trailingIcon에다가 weight(1f)짜리 박스를 Row로 붙여놨던 것 같은데 그것보다는 이게 훨씬 낫겠다

2023-07-11 13:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/components/compose/WebViewStyleButton.kt
> +    disabledColor: Color = SNUTTColors.Gray400,
초기값 👍

2023-07-11 13:57 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/network/SNUTTRestApi.kt
> +    @POST("/user/email/verification/code")
다빈이형이 옛날부터 다 붙여달라 했는데 빼먹고 안 붙인 게 좀 있어서 싹 붙임
얘도 붙이기 ㄱㄱ

2023-07-11 13:59 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
홈키 눌러서 백그라운드 갔다가 오래 있어서 날아갈 수도 있고, 여러가지로 그게 딱 1초라고 보장할 수 없으니까

2023-07-11 14:04 UTC, JuTaK97 requested changes

2023-07-11 14:04 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignUpPage.kt
> +                    verticalArrangement = Arrangement.spacedBy(6.dp)
```suggestion
                    verticalArrangement = Arrangement.spacedBy(10.dp)
```

2023-07-11 14:04 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignUpPage.kt
> +                    verticalArrangement = Arrangement.spacedBy(6.dp)
```suggestion
                    verticalArrangement = Arrangement.spacedBy(10.dp)
```

2023-07-11 14:04 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/SignUpPage.kt
> +                    verticalArrangement = Arrangement.spacedBy(6.dp)
```suggestion
                    verticalArrangement = Arrangement.spacedBy(10.dp)
```

2023-07-12 10:11 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
그렇군.... currentTimeMillis 이용하도록 수정해봤는데 한 번 봐주세용

2023-07-18 14:17 UTC, JuTaK97 commented
타이머 관련해서는 더 좋은 방법에 대해 고민해봐야겠어

2023-07-18 14:30 UTC, JuTaK97 commented
- 하고 싶은 것 
비번 재설정 인증번호 메일을 보내고 유저는 앱을 백그라운드로 내리고 메일을 확인할 텐데, 이때 실수로 or 시스템에 의해 액티비티가 destroy되면? 앱을 다시 켰을 때 싹다 날아가고 처음부터 해야 한다. 
상태를 유지시켜서 딥링크(와 비슷한 형태)로 바로 재설정 인증번호 화면으로 이동시키고, 타이머까지 시간이 잘 계산된 채로 다시 돌아가기 시작하게 하고 싶다.

2023-07-18 14:39 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
시간 만료되고 다시 요청 누르면 타이머 초기화 안 되는듯?

2023-07-19 10:57 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_out/VerifyEmailPage.kt
> +        endTime = 180,
헉 수정했어요

2023-07-23 11:09 UTC, JuTaK97 approved these changes
일단 OK인데 타이머 쪽은 추후에 같이 다시 고쳐봅시다

2023-07-23 11:59 UTC, merged