LectureDetail에서 보여주는 ClassTime Text Format fix
wafflestudio/snutt-android pull request #364
Opened 2024-10-09 11:11 UTC by plgafhd

- 전에 빈자리 알림 ui 피그마랑 맞춘다고 이 부분을 건드린 적이 있는데, 그 이후로 LectureDeatilPage에서는 이상하게 보여주고 있었다...
- 강의계획서 referer 보다가 갑자기 발견해서 fix

2024-10-13 09:08 UTC, eastshine2741 requested changes, later dismissed

2024-10-13 09:08 UTC, eastshine2741 commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
> +    }
함수 2개로 분리하고 kdoc으로 주석적어줘

2024-10-13 14:40 UTC, plgafhd commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
> +    }
[1b65151](https://github.com/wafflestudio/snutt-android/pull/364/commits/1b651512114330f342f05533cb55959fa28cd9a5)

2024-10-14 02:36 UTC, plgafhd commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
> +    }
아놔... 주석을 잘못 달았군... 나중에 수정해야겠다... ㅋㅋㅋㅋ

2024-10-16 08:18 UTC, plgafhd commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
> +    }
[6f52a9b](https://github.com/wafflestudio/snutt-android/pull/364/commits/6f52a9bd9f3b5e408a895cf017846fc5429b811a)
여기서 수정

2024-10-16 15:25 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
>      }
```suggestion
    fun getSimplifiedClassTimeForLecture(lectureDto: LectureDto): String {
        if (lectureDto.class_time_json.isEmpty()) {
            return "(없음)"
        }

        return lectureDto.class_time_json.joinToString(", ", transform = ::getClassTimeTextForLecture)
    }
```

2024-10-16 15:27 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
>      }
아이게아니군

2024-10-19 04:13 UTC, plgafhd commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
>      }
[b444686](https://github.com/wafflestudio/snutt-android/pull/364/commits/b4446865b5a86c1c6d19268c2e7f3fe6b005fbbf)
오 이런 방법이

2024-10-19 04:14 UTC, plgafhd commented on app/src/main/java/com/wafflestudio/snutt2/lib/data/SNUTTStringUtils.kt
> +        append("%02d:%02d".format(classTime.endTimeHour, classTime.endTimeMinute))
이 참에 얘도 StringBuilder()에서 buildString{}으로 바꿔봤어 (사소)

2024-10-19 06:28 UTC, JuTaK97 approved these changes
굿~

2024-10-23 17:31 UTC, plgafhd commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2024-10-23 17:43 UTC, merged