TableLecturesFragment에 Jetpack Compose 적용
wafflestudio/snutt-android pull request #55
Opened 2022-04-09 16:55 UTC by JuTaK97

- API를 써서 pagingdata를 가져오던 notification과는 다르게 TableLectures에서는 `storage.lastViewedTable`를 가져오기 때문에 flow를 어떻게 쓰는 게 맞는 건지 고민이 됩니다.<br /> 일단은 억지로  `storage.lastViewedTable`에서 `get()`으로 내용을 추출해서 `flowOf(PagingData.from())` 으로 flow와 lazypaging을 적용해 놓은 상태입니다. 
- Adapter나 xml 파일은 추후 피드백 적용할 때 디테일적인 면에서 참고할 수도 있을 것 같아 일단 남겨놨습니다.
- NoficationFragment 만들 때 쓴 TopBar() 함수를 재사용했습니다. 괜찮은 걸까요?
- TextStyle을 일일히 Composable마다 private val로 지정하는 것이 예쁘지 않은 것 같습니다. 대체할 방법을 찾고 있습니다.
- 굳이 TableLectures에서 PagingItem과 lazycolumn을 쓸 필요가 있을까요? 없을 것 같지만 일단 이렇게 해 봤습니다.
- 현재 onClick에서 다중 클릭 방지가 적용되지 않은 상태입니다. 코루틴으로 뭔가 할 수 있는 것 같은데 좀 더 공부하고 적용해 보겠습니다.
- 앱에서 클릭에 의한 화면 전환이 묘하게 뻑뻑합니다. 원인은 잘 모르겠지만 찾아보는 중입니다.
- clickable에서, <br />
```kotlin
                    .clickable(
                        onClick = { onClickLecture.invoke(data.lecture) },
                        indication = null,
                        interactionSource = MutableInteractionSource()
                    )
```
이렇게 했던 이유를 기억해 냈습니다. 클릭 시 ripple effect를 없애기 위해서였습니다.

2022-05-28 06:52 UTC, sanggggg requested changes

2022-05-28 06:52 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +                    if (it.isEmpty()) "(없음)" else it.joinToString(", ")
stringResource 로 빼기?

2022-05-28 06:52 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +            if (classTimeText.isEmpty()) classTimeText = "(없음)"
getSimplefiedClassTime 에서 `(없음)` 텍스트 까지 넣어주도록 하는게 좋을 것 같아요
+불필요한 var 를 지양하는게 좋을 것 같습니다

2022-05-28 06:52 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +                    )
[nit]
`fun Modifier.clickalbeWithoutRippleEffect(...)` 로 추출하기?

2022-05-28 06:52 UTC, sanggggg commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +                        Text(text = data.lecture.instructor + " / " + data.lecture.credit + "학점", style = detailFontStyle)
SNUTTStringUtil 로 빼기?

2022-06-10 07:07 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +                    if (it.isEmpty()) "(없음)" else it.joinToString(", ")
[https://github.com/wafflestudio/SNUTT-android/pull/55/commits/64950626f1789fbde1e387237b0de8155c814208](반영)

2022-06-10 07:08 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +            if (classTimeText.isEmpty()) classTimeText = "(없음)"
[피드백 반영 commit](https://github.com/wafflestudio/SNUTT-android/pull/55/commits/64950626f1789fbde1e387237b0de8155c814208)

2022-06-10 07:09 UTC, JuTaK97 commented on app/src/main/java/com/wafflestudio/snutt2/views/logged_in/table_lectures/TableLecturesComposable.kt
> +                    )
[피드백 반영 commit](https://github.com/wafflestudio/SNUTT-android/pull/55/commits/8debe2c7e0f2620608a81a755978cae56162af49#diff-977505794c8a6894d3ebf9169ccbedf1e1489400568a6852f96da8a40884ce32R42)

2022-08-06 07:44 UTC, closed without merging